"""Tests for the IGNITE L2 Reporter."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from ignite_parser.analyzer import (
    AnalysisResult,
    CoverageReport,
    DependencyEdge,
    DependencyGraph,
    EndpointRecord,
    FindingCluster,
    analyze,
)
from ignite_parser.models import (
    AgentRole,
    Confidence,
    Finding,
    FindingCategory,
    FindingConfidence,
    Interaction,
    Observation,
    Relationships,
    Request,
    Response,
    Span,
    SpanKind,
    Trace,
    TraceStatus,
)
from ignite_parser.parser import parse_trace
from ignite_parser.reporter import generate_report


FIXTURE_DIR = Path(__file__).parent / "fixtures"


# --- Helpers ---

def _make_span(
    span_id: str,
    kind: SpanKind = SpanKind.API_CALL,
    target: str = "",
    method: str | None = None,
    url: str | None = None,
    status_code: int | None = None,
    body_schema: dict | None = None,
    request_body: dict | None = None,
    error: str | None = None,
    what_happened: str = "tested",
    what_learned: str = "learned something",
    confidence: Confidence = Confidence.HIGH,
    questions: list[str] | None = None,
    enables: list[str] | None = None,
    tags: list[str] | None = None,
    sequence: int = 1,
) -> Span:
    return Span(
        span_id=span_id,
        trace_id="trace-1",
        sequence=sequence,
        kind=kind,
        started_at=datetime(2026, 7, 24, 14, 0, tzinfo=timezone.utc),
        interaction=Interaction(
            target=target,
            method=method,
            request=Request(url=url, body=request_body),
            response=Response(status_code=status_code, body_schema=body_schema, error=error),
        ),
        observation=Observation(
            what_happened=what_happened,
            what_learned=what_learned,
            confidence=confidence,
            questions_raised=questions or [],
        ),
        relationships=Relationships(enables=enables or []),
        tags=tags or [],
    )


def _make_finding(
    finding_id: str,
    category: FindingCategory = FindingCategory.PROTOCOL,
    title: str = "Test finding",
    description: str = "A test finding description",
    confidence: FindingConfidence = FindingConfidence.CONFIRMED,
    source_spans: list[str] | None = None,
) -> Finding:
    return Finding(
        finding_id=finding_id,
        trace_id="trace-1",
        source_spans=source_spans or [],
        category=category,
        title=title,
        description=description,
        confidence=confidence,
    )


def _make_trace(
    trace_id: str = "trace-1",
    system: str = "plaid",
    spans: list[Span] | None = None,
    findings: list[Finding] | None = None,
) -> Trace:
    return Trace(
        schema_version="0.1",
        trace_id=trace_id,
        agent_id="TestAgent",
        agent_role=AgentRole.EXPLORER,
        system=system,
        started_at=datetime(2026, 7, 24, 14, 0, tzinfo=timezone.utc),
        status=TraceStatus.COMPLETED,
        objective="Test objective",
        spans=spans or [],
        findings=findings or [],
    )


# --- Report structure tests ---

def test_report_empty_analysis():
    result = analyze([])
    report = generate_report(result)
    assert "# IGNITE Trace Analysis Report" in report
    assert "Executive Summary" in report
    assert "Traces analyzed | 0" in report


def test_report_has_all_sections():
    span = _make_span("s1", target="/test", method="GET", status_code=200,
                       enables=["s2"], questions=["Rate limit?"])
    span2 = _make_span("s2", target="/test2", method="POST", status_code=201, sequence=2)
    finding = _make_finding("f1", source_spans=["s1"])
    trace = _make_trace(spans=[span, span2], findings=[finding])
    result = analyze([trace])
    report = generate_report(result)

    assert "## Executive Summary" in report
    assert "## Endpoint Catalog" in report
    assert "## Findings" in report
    assert "## Dependency Map" in report
    assert "## Coverage & Gaps" in report
    assert "## Open Questions" in report
    assert "Generated by IGNITE L2 Pipeline" in report


def test_report_custom_title():
    result = analyze([])
    report = generate_report(result, title="Plaid Study Report")
    assert "# Plaid Study Report" in report


def test_report_system_filter():
    result = analyze([])
    report = generate_report(result, system="plaid")
    assert "**System:** plaid" in report


# --- Executive Summary ---

def test_summary_counts():
    span = _make_span("s1", target="/test", method="GET")
    finding = _make_finding("f1")
    trace = _make_trace(spans=[span], findings=[finding])
    result = analyze([trace])
    report = generate_report(result)

    assert "Traces analyzed | 1" in report
    assert "Spans processed | 1" in report
    assert "Findings extracted | 1" in report


# --- Endpoint Catalog ---

def test_endpoint_details():
    span = _make_span(
        "s1", target="/link/token/create", method="POST",
        url="https://sandbox.plaid.com/link/token/create",
        status_code=200, tags=["link", "auth"],
        what_learned="Token has 4hr TTL",
        questions=["Refresh possible?"],
    )
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert "`POST /link/token/create`" in report
    assert "sandbox.plaid.com" in report
    assert "200" in report
    assert "Token has 4hr TTL" in report
    assert "Refresh possible?" in report


def test_endpoint_error_patterns():
    span = _make_span("s1", target="/test", method="GET", error="INVALID_TOKEN")
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert "INVALID_TOKEN" in report
    assert "Error patterns" in report


def test_endpoint_with_schemas():
    req_body = {"client_id": "[REDACTED]", "products": ["transactions"]}
    resp_schema = {"type": "object", "properties": {"link_token": {"type": "string"}}}
    span = _make_span("s1", target="/test", method="POST",
                       request_body=req_body, body_schema=resp_schema)
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert '"client_id"' in report
    assert '"link_token"' in report
    assert "Request body" in report
    assert "Response schema" in report


# --- Findings ---

def test_findings_sorted_by_confidence():
    f1 = _make_finding("f1", title="Hypothesis finding", confidence=FindingConfidence.HYPOTHESIS)
    f2 = _make_finding("f2", title="Confirmed finding", confidence=FindingConfidence.CONFIRMED)
    trace = _make_trace(findings=[f1, f2])
    result = analyze([trace])
    report = generate_report(result)

    # Confirmed should appear before hypothesis
    confirmed_pos = report.index("Confirmed finding")
    hypothesis_pos = report.index("Hypothesis finding")
    assert confirmed_pos < hypothesis_pos


def test_findings_confidence_emoji():
    f1 = _make_finding("f1", confidence=FindingConfidence.CONFIRMED)
    trace = _make_trace(findings=[f1])
    result = analyze([trace])
    report = generate_report(result)

    assert "✅" in report


def test_findings_cluster_count():
    f1 = _make_finding("f1", title="Same finding")
    f2 = _make_finding("f2", title="Same finding")
    t1 = _make_trace(trace_id="t1", findings=[f1])
    t2 = _make_trace(trace_id="t2", findings=[f2])
    result = analyze([t1, t2])
    report = generate_report(result)

    assert "2 trace(s)" in report


# --- Dependency Map ---

def test_dependency_map_edges():
    span1 = _make_span("s1", target="/a", enables=["s2"])
    span2 = _make_span("s2", target="/b", sequence=2)
    trace = _make_trace(spans=[span1, span2])
    result = analyze([trace])
    report = generate_report(result)

    assert "Dependency Map" in report
    assert "s1 → s2" in report


def test_dependency_map_topology():
    span1 = _make_span("s1", target="/a", enables=["s2"])
    span2 = _make_span("s2", target="/b", sequence=2)
    trace = _make_trace(spans=[span1, span2])
    result = analyze([trace])
    report = generate_report(result)

    assert "Entry points" in report or "Terminal nodes" in report


# --- Coverage ---

def test_coverage_span_kinds():
    span = _make_span("s1", kind=SpanKind.API_CALL, target="/test")
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert "api_call" in report
    assert "✅ Observed" in report
    assert "Not yet explored" in report


def test_coverage_low_confidence():
    span = _make_span("s1", target="/maybe", method="GET",
                       confidence=Confidence.LOW, what_learned="Might work")
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert "Low-Confidence Areas" in report
    assert "Might work" in report


# --- Open Questions ---

def test_open_questions_numbered():
    span = _make_span("s1", target="/test", method="GET",
                       questions=["What is the rate limit?", "Does it paginate?"])
    trace = _make_trace(spans=[span])
    result = analyze([trace])
    report = generate_report(result)

    assert "1. What is the rate limit?" in report
    assert "2. Does it paginate?" in report


# --- Integration: fixture file ---

def test_report_from_fixture():
    """Full pipeline: fixture JSON → Parser → Analyzer → Reporter."""
    fixture = FIXTURE_DIR / "valid_trace.json"
    with open(fixture) as f:
        data = json.load(f)

    parse_result = parse_trace(data)
    assert parse_result.ok

    analysis = analyze(parse_result.traces)
    report = generate_report(analysis, title="Plaid Link Study", system="plaid")

    # Verify key content surfaces
    assert "# Plaid Link Study" in report
    assert "**System:** plaid" in report
    assert "POST" in report
    assert "link_token" in report
    assert "4" in report  # 4-hour TTL mentioned somewhere
    assert "Open Questions" in report
    assert "Generated by IGNITE L2 Pipeline" in report
    # Report should be substantial
    assert len(report) > 500
